#! /bin/bash

aarch64-linux-gnu-as boot.S -o boot.o
aarch64-linux-gnu-gcc -ffreestanding -c kernel.c -o kernel.o
aarch64-linux-gnu-ld -nostdlib -T linker.ld boot.o kernel.o -o kernel.elf

qemu-system-aarch64 -machine virt -nographic -cpu cortex-a72 -kernel kernel.elf
# qemu-system-aarch64 -machine virt,virtualization=on,secure=on -nographic -cpu cortex-a72 -kernel build/kernel.elf
